# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nice_nano_v2
    shield: kyria_left
    cmake-args: "-DCONFIG_ZMK_KEYBOARD_NAME='\"Kyria #1\"'"
  - board: nice_nano_v2
    shield: kyria_right
    cmake-args: "-DCONFIG_ZMK_KEYBOARD_NAME='\"Kyria #1\"'"
  - board: nice_nano_v2
    shield: kyria_left
    cmake-args: "-DCONFIG_ZMK_KEYBOARD_NAME='\"Kyria #2\"'
                 -DCONFIG_ZMK_RGB_UNDERGLOW=n"
  - board: nice_nano_v2
    shield: kyria_right
    cmake-args: "-DCONFIG_ZMK_KEYBOARD_NAME='\"Kyria #2\"'
                 -DCONFIG_ZMK_RGB_UNDERGLOW=n"
