CONFIG_ZMK_DISPLAY=n

# For macros longer than 30 characters
CONFIG_ZMK_BEHAVIORS_QUEUE_SIZE=256

CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=60000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=600000

CONFIG_ZMK_USB_LOGGING=n
